import { on } from "@ember/modifier";
import RouteTemplate from "ember-route-template";
import getURL from "discourse/lib/get-url";
import { i18n } from "discourse-i18n";
const overviewUrl = getURL("/admin/plugins/account-security");
const settingsUrl = getURL("/admin/site_settings/category/all_results?filter=account_security");
export default RouteTemplate(<template>
  <div class="as-admin">
    <section class="as-admin__hero"><div class="as-admin__hero-copy"><h1>{{i18n "admin.account_security.health.title"}}</h1><p>{{i18n "admin.account_security.health.description"}}</p></div><div class="as-admin__hero-actions"><a class="btn" href={{overviewUrl}}>{{i18n "admin.account_security.back_overview"}}</a><a class="btn" href={{settingsUrl}}>{{i18n "admin.account_security.open_settings"}}</a></div></section>
    {{#if this.data}}
      <section class="as-admin__section"><div class="as-admin__metrics"><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.health.overall"}}</div><div class="as-admin__metric-value">{{this.data.overall}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.health.provider"}}</div><div class="as-admin__metric-value">{{this.data.provider.status}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.remaining_checks"}}</div><div class="as-admin__metric-value">{{if this.data.provider.status this.data.provider.remaining "—"}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.health.circuit"}}</div><div class="as-admin__metric-value">{{this.data.circuit_breaker.state}}</div></div></div></section>
      <section class="as-admin__grid"><div class="as-admin__panel"><h2>{{i18n "admin.account_security.health.configuration"}}</h2><p><strong>{{i18n "admin.account_security.health.api_key"}}:</strong> {{this.data.configuration.api_key_configured}}</p><p><strong>{{i18n "admin.account_security.health.terms"}}:</strong> {{this.data.configuration.usage_terms_acknowledged}}</p><p><strong>{{i18n "admin.account_security.health.reporting"}}:</strong> {{this.data.configuration.abuse_reporting_enabled}}</p></div><div class="as-admin__panel"><h2>{{i18n "admin.account_security.health.feeds"}}</h2><p><strong>Tor:</strong> {{this.data.feeds.tor.status}} / {{this.data.feeds.tor.entry_count}}</p><p><strong>AbuseIPDB blacklist:</strong> {{this.data.feeds.abuseipdb_blacklist.status}} / {{this.data.feeds.abuseipdb_blacklist.entry_count}}</p></div><div class="as-admin__panel"><h2>{{i18n "admin.account_security.health.privacy"}}</h2><p>{{i18n "admin.account_security.health.privacy_text"}}</p></div></section>
      <section class="as-admin__panel"><div class="as-admin__buttons"><button class="btn btn-primary" type="button" disabled={{this.isTesting}} {{on "click" this.runTest}}>{{i18n "admin.account_security.health.test"}}</button><button class="btn" type="button" {{on "click" this.resetCircuit}}>{{i18n "admin.account_security.health.reset_circuit"}}</button></div><p class="as-admin__hint">{{i18n "admin.account_security.health.test_hint"}}</p>{{#if this.data.test_result}}<p><strong>{{i18n "admin.account_security.health.test_result"}}:</strong> {{this.data.test_result.success}} / {{if this.data.test_result.error_code this.data.test_result.error_code this.data.test_result.status}}</p>{{/if}}</section>
    {{else}}<p class="as-admin__muted">{{i18n "admin.account_security.loading"}}</p>{{/if}}
  </div>
</template>);
