import { on } from "@ember/modifier";
import RouteTemplate from "ember-route-template";
import getURL from "discourse/lib/get-url";
import { i18n } from "discourse-i18n";
const overviewUrl = getURL("/admin/plugins/account-security");
export default RouteTemplate(<template>
  <div class="as-admin">
    <section class="as-admin__hero"><div class="as-admin__hero-copy"><h1>{{i18n "admin.account_security.statistics.title"}}</h1><p>{{i18n "admin.account_security.statistics.description"}}</p></div><div class="as-admin__hero-actions"><a class="btn" href={{overviewUrl}}>{{i18n "admin.account_security.back_overview"}}</a></div></section>
    <section class="as-admin__panel"><div class="as-admin__field"><label>{{i18n "admin.account_security.statistics.period"}}</label><select {{on "change" this.setPeriod}}><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option><option value="365">365 days</option></select></div></section>
    {{#if this.data}}<section class="as-admin__section"><div class="as-admin__metrics"><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.statistics.assessments"}}</div><div class="as-admin__metric-value">{{this.data.totals.assessments}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.statistics.provider_calls"}}</div><div class="as-admin__metric-value">{{this.data.totals.provider_calls}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.statistics.cache_hits"}}</div><div class="as-admin__metric-value">{{this.data.totals.cache_hits}}</div></div><div class="as-admin__metric"><div class="as-admin__metric-label">{{i18n "admin.account_security.statistics.events"}}</div><div class="as-admin__metric-value">{{this.data.totals.events_created}}</div></div></div></section><section class="as-admin__panel"><div class="as-admin__table-wrap"><table class="as-admin__table"><thead><tr><th>Date</th><th>Assessments</th><th>Provider</th><th>Cache</th><th>Blacklist</th><th>Tor</th><th>Quota skips</th><th>Events</th></tr></thead><tbody>{{#each this.data.daily as |day|}}<tr><td>{{day.stat_date}}</td><td>{{day.assessments}}</td><td>{{day.provider_calls}}</td><td>{{day.cache_hits}}</td><td>{{day.local_blacklist_hits}}</td><td>{{day.tor_hits}}</td><td>{{day.quota_skips}}</td><td>{{day.events_created}}</td></tr>{{/each}}</tbody></table></div></section>{{else}}<p class="as-admin__muted">{{i18n "admin.account_security.loading"}}</p>{{/if}}
  </div>
</template>);
